name: flutter_fast_supabase
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  auto_route: ^9.2.2
  get_it: ^7.7.0
  injectable: ^2.4.4
  flutter:
    sdk: flutter
  supabase_flutter: ^2.6.0 
  shared_preferences: 2.3.2

dev_dependencies:
  build_runner: ^2.4.11
  auto_route_generator: ^9.0.0
  injectable_generator: ^2.6.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true